// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import DatabaseOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
import BuildOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/BuildOutlined';
import PlayCircleOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/PlayCircleOutlined';
import SettingOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import UsergroupAddOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/UsergroupAddOutlined';
import FontColorsOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/FontColorsOutlined';
import UserOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/UserOutlined';
import MenuUnfoldOutlined from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/MenuUnfoldOutlined';
export default { SmileOutlined, CrownOutlined, DatabaseOutlined, BuildOutlined, PlayCircleOutlined, SettingOutlined, UsergroupAddOutlined, FontColorsOutlined, UserOutlined, MenuUnfoldOutlined };
