// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/huangchao/IdeaProjects/SuperHuang/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/huangchao/IdeaProjects/SuperHuang/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import SettingOutlined from '/Users/huangchao/IdeaProjects/SuperHuang/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import UsergroupAddOutlined from '/Users/huangchao/IdeaProjects/SuperHuang/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/UsergroupAddOutlined';
import FontColorsOutlined from '/Users/huangchao/IdeaProjects/SuperHuang/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/FontColorsOutlined';
import UserOutlined from '/Users/huangchao/IdeaProjects/SuperHuang/data_scalpel3/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, CrownOutlined, SettingOutlined, UsergroupAddOutlined, FontColorsOutlined, UserOutlined };
