// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-locale';
export { Provider, useModel } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-access/types.d';
export * from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-antd/types.d';
export * from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-layout/types.d';
export * from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@umijs+renderer-react@4.3.17_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/@umijs+renderer-react@4.3.17_react-dom@18.3.1_react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/dwx/Desktop/workspace/gistack/data_scalpel3/node_modules/.pnpm/umi@4.3.17_@babel+core@7.25.2_@types+node@22.5.0_@types+react@18.3.4_eslint@8.35.0_jest@29.7._vgocb76k6awtfuq2xlu7xtxzia/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
